update=4/24/2018 11:13:29 AM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Capacitor
LibName2=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Capacitor_Polarized
LibName3=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Circuit_Protection
LibName4=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Connector
LibName5=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Crystal
LibName6=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Diode
LibName7=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Analog
LibName8=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Data_Conversion
LibName9=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Digital
LibName10=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Interface
LibName11=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_Power
LibName12=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_IC_RF
LibName13=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Inductor_Fixed
LibName14=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Inductor_Variable
LibName15=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Misc
LibName16=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Module
LibName17=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Optoisolator
LibName18=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Potentiometer
LibName19=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_power
LibName20=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Relay
LibName21=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Resistor
LibName22=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Sensor
LibName23=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Switch
LibName24=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Symbol
LibName25=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Transformer
LibName26=C:/Users/alitton/Dropbox/Github/KiCad.lib/Celeritous_Transistor
